<a href="https://colab.research.google.com/github/ZubrilinAO/GB-Practice/blob/main/Python/HW_Seminar_10/Sem10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Задание 44

В ячейке ниже представлен код генерирующий DataFrame, которая состоит всего из 1 столбца. Ваша задача перевести его в one hot вид. Сможете ли вы это сделать без get_dummies?

In [62]:
import pandas as pd
import random


lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()

  whoAmI
0  human
1  human
2  human
3  robot
4  human

In [81]:
pd.get_dummies(data).head()

   whoAmI_human  whoAmI_robot
0             1             0
1             1             0
2             1             0
3             0             1
4             1             0

In [82]:
def my_get_dummies(data_frame):
    name_col = data_frame.columns.values[0]
    data_list =  data_frame[name_col].values.tolist()
    values = list(set(data_list))
    values.sort()

    hot_list = list()
    for item in data_list:
      hot_data_list = list()  
      for val in values:  
        if item == val:
          hot_data_list.append(1)
        else:
          hot_data_list.append(0)
      hot_list.append(hot_data_list)
    values = list(map(lambda x:  name_col + '_' + x ,  values))

    return pd.DataFrame(hot_list, columns=values)
    

my_get_dummies(data).head()

   whoAmI_human  whoAmI_robot
0             1             0
1             1             0
2             1             0
3             0             1
4             1             0